apiVersion: v1
kind: Service
metadata:
  name: front-end-service
  labels:
    app: foodie-front-end
spec:
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: foodie
  type: LoadBalancer
